import { Ubuntu } from "next/font/google";
import Header from "@/components/header";
import "../styles/index.scss";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="nl">
        <body className={ubuntu.className}>
            <Header/>
            {children}
        </body>
    </html>
  );
}
